### ISSUE TITLE
NameError: name 'config' is not defined

### ISSUE THREAD

**Issue by xyjtokushima** [fucusy/gait-energy-image-recognition#3]
我下载完剪影库，并设置好路径之后，运行main，却发生了错误，NameError: name 'config' is not defined。如图，请问我应该怎么解决呢？
![image](https://user-images.githubusercontent.com/41357251/42888660-a92bd854-8ae3-11e8-9690-f95e5a20a7cc.png)

**Comment by fucusy** [comment]
你可以试着在命令行当中运行这个文件吗？也就是终端，terminal

**Comment by Cuervo** [comment]
I run the program from terminal and i get this error:
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    , val_dir=val_dir)
  File "/home/mr-crow/Programas en Python/Gait Recognition/gait-energy-image-recognition-gei/data_tool.py", line 40, in load_training_validation_data
    data = img_path_to_GEI(img_dir)
  File "/home/mr-crow/Programas en Python/Gait Recognition/gait-energy-image-recognition-gei/tool.py", line 227, in img_path_to_GEI
    cache_file = "%s/%s_GEI.npy" % (config.Project.test_data_path, id)
NameError: global name 'config' is not defined

Does anyone know how to fix it?

**Comment by forestyang-402** [comment]
您好,请问您能不能给一个路径设置的例子呢

**Comment by segeramanda** [comment]
Hello! I get the same error.  

File "main.py", line 33, in <module>
    , val_dir=val_dir)
  File "/Users/amandaseger/Documents/EXJOBB/Code_test/gait-energy-image-recognition/data_tool.py", line 40, in load_training_validation_data
    data = img_path_to_GEI(img_dir)
  File "/Users/amandaseger/Documents/EXJOBB/Code_test/gait-energy-image-recognition/tool.py", line 228, in img_path_to_GEI
    cache_file = "%s/%s_GEI.npy" % (config.Project.test_data_path, id)
NameError: name 'config' is not defined
